services:
  wetty:
    image: wettyoss/wetty
    build:
      context: .
      dockerfile: containers/wetty/Dockerfile
    entrypoint: pnpm run docker-compose-entrypoint
    ports:
      - '8100:3000'
    environment:
      - SSHHOST=${SSHHOST}
      - BASE=/pidev/

  web:
    image: nginx
    volumes:
      - ./conf/nginx.template:/etc/nginx/conf.d/wetty.template
    ports:
      - '80:80'
    environment:
      - NGINX_DOMAIN=wetty.com
      - NGINX_PORT=80
      - WETTY_HOST=wetty
      - WETTY_PORT=3000
    command: >-
      /bin/bash -c "envsubst
      '$${NGINX_DOMAIN},$${NGINX_PORT},$${WETTY_HOST},$${WETTY_PORT}' <
      /etc/nginx/conf.d/wetty.template > /etc/nginx/conf.d/default.conf && nginx
      -g 'daemon off;'"

  wetty-ssh:
    build:
      context: .
      dockerfile: containers/ssh/Dockerfile
    image: wettyoss/wetty:ssh

networks:
  default:
    name: wetty
